In [1]:
#1. Load the MallCustomer dataset in dataframe object df
#2. Display summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset for each column
#3. Display Measures of Dispersion ( Mean Absolute Deviation, Variance, Standard Deviation,Range, Quartiles, Skewness)
#4. if your categorical variable is age groupsa nd quantitative variable is income, then provide summary statistics (minimum and maximum) of income grouped by the age groups.
 
import pandas as pd
import numpy as np
import matplotlib as ml
df=pd.read_csv("Mall_Customers.csv")
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
..          ...     ...  ...                 ...                     ...
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [3]:
df.mean()#all data mean

CustomerID                100.50
Age                        38.85
Annual Income (k$)         60.56
Spending Score (1-100)     50.20
dtype: float64

In [5]:
df['Age'].mean()#for particular value mean

38.850000000000001

In [6]:
df.median()#meadian for all values

CustomerID                100.5
Age                        36.0
Annual Income (k$)         61.5
Spending Score (1-100)     50.0
dtype: float64

In [8]:
df['Age'].median()#for particular data

36.0

In [9]:
df.mode()

     CustomerID   Genre   Age  Annual Income (k$)  Spending Score (1-100)
0             1  Female  32.0                54.0                    42.0
1             2     NaN   NaN                78.0                     NaN
2             3     NaN   NaN                 NaN                     NaN
3             4     NaN   NaN                 NaN                     NaN
4             5     NaN   NaN                 NaN                     NaN
5             6     NaN   NaN                 NaN                     NaN
6             7     NaN   NaN                 NaN                     NaN
7             8     NaN   NaN                 NaN                     NaN
8             9     NaN   NaN                 NaN                     NaN
9            10     NaN   NaN                 NaN                     NaN
10           11     NaN   NaN                 NaN                     NaN
11           12     NaN   NaN                 NaN                     NaN
12           13     NaN   NaN                 NaN                     NaN
13           14     NaN   NaN                 NaN                     NaN
14           15     NaN   NaN                 NaN                     NaN
15           16     NaN   NaN                 NaN                     NaN
16           17     NaN   NaN                 NaN                     NaN
17           18     NaN   NaN                 NaN                     NaN
18           19     NaN   NaN                 NaN                     NaN
19           20     NaN   NaN                 NaN                     NaN
20           21     NaN   NaN                 NaN                     NaN
21           22     NaN   NaN                 NaN                     NaN
22           23     NaN   NaN                 NaN                     NaN
23           24     NaN   NaN                 NaN                     NaN
24           25     NaN   NaN                 NaN                     NaN
25           26     NaN   NaN                 NaN                     NaN
26           27     NaN   NaN                 NaN                     NaN
27           28     NaN   NaN                 NaN                     NaN
28           29     NaN   NaN                 NaN                     NaN
29           30     NaN   NaN                 NaN                     NaN
..          ...     ...   ...                 ...                     ...
170         171     NaN   NaN                 NaN                     NaN
171         172     NaN   NaN                 NaN                     NaN
172         173     NaN   NaN                 NaN                     NaN
173         174     NaN   NaN                 NaN                     NaN
174         175     NaN   NaN                 NaN                     NaN
175         176     NaN   NaN                 NaN                     NaN
176         177     NaN   NaN                 NaN                     NaN
177         178     NaN   NaN                 NaN                     NaN
178         179     NaN   NaN                 NaN                     NaN
179         180     NaN   NaN                 NaN                     NaN
180         181     NaN   NaN                 NaN                     NaN
181         182     NaN   NaN                 NaN                     NaN
182         183     NaN   NaN                 NaN                     NaN
183         184     NaN   NaN                 NaN                     NaN
184         185     NaN   NaN                 NaN                     NaN
185         186     NaN   NaN                 NaN                     NaN
186         187     NaN   NaN                 NaN                     NaN
187         188     NaN   NaN                 NaN                     NaN
188         189     NaN   NaN                 NaN                     NaN
189         190     NaN   NaN                 NaN                     NaN
190         191     NaN   NaN                 NaN                     NaN
191         192     NaN   NaN                 NaN                     NaN
192         193     NaN   NaN                 NaN                     NaN
193         194     NaN   NaN                 NaN                     NaN
194         195     NaN   NaN                 NaN                     NaN
195         196     NaN   NaN                 NaN                     NaN
196         197     NaN   NaN                 NaN                     NaN
197         198     NaN   NaN                 NaN                     NaN
198         199     NaN   NaN                 NaN                     NaN
199         200     NaN   NaN                 NaN                     NaN

[200 rows x 5 columns]

In [11]:
df['Age'].mode()#for particular value

0    32
dtype: int64

In [12]:
df.std()#for standard deviation

CustomerID                57.879185
Age                       13.969007
Annual Income (k$)        26.264721
Spending Score (1-100)    25.823522
dtype: float64

In [13]:
df['Age'].max() - df['Age'].min()#for Range

52

In [14]:
df.var()#for variance

CustomerID                3350.000000
Age                        195.133166
Annual Income (k$)         689.835578
Spending Score (1-100)     666.854271
dtype: float64

In [15]:
df.quantile()#for quantile

CustomerID                100.5
Age                        36.0
Annual Income (k$)         61.5
Spending Score (1-100)     50.0
Name: 0.5, dtype: float64

In [16]:
df.skew()# for skewness

CustomerID                0.000000
Age                       0.485569
Annual Income (k$)        0.321843
Spending Score (1-100)   -0.047220
dtype: float64

In [3]:
df.groupby('Genre')['Age'].mean()# 3. Grouped Summary Statistics (e.g., Income by Genre)

Genre
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [7]:
df.groupby('Genre')['Annual Income (k$)'].mean()

Genre
Female    59.250000
Male      62.227273
Name: Annual Income (k$), dtype: float64

In [10]:
from sklearn import preprocessing#used in ML for converting values into 0s and 1s
enc= preprocessing.OneHotEncoder()
enc_df=pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())
df_encoded=df.join(enc_df)
df_encoded

,CustomerID,Genre,Age,Annual Income (k$),Spending Score (1-100),0,1
0,1,Male,19,15,39,0.0,1.0
1,2,Male,21,15,81,0.0,1.0
2,3,Female,20,16,6,1.0,0.0
3,4,Female,23,16,77,1.0,0.0
4,5,Female,31,17,40,1.0,0.0
5,6,Female,22,17,76,1.0,0.0
6,7,Female,35,18,6,1.0,0.0
7,8,Female,23,18,94,1.0,0.0
8,9,Male,64,19,3,0.0,1.0
9,10,Female,30,19,72,1.0,0.0
10,11,Male,67,19,14,0.0,1.0
11,12,Female,35,19,99,1.0,0.0
12,13,Female,58,20,15,1.0,0.0
13,14,Female,24,20,77,1.0,0.0
14,15,Male,37,20,13,0.0,1.0
15,16,Male,22,20,79,0.0,1.0
16,17,Female,35,21,35,1.0,0.0
17,18,Male,20,21,66,0.0,1.0
18,19,Male,52,23,29,0.0,1.0
19,20,Female,35,23,98,1.0,0.0
20,21,Male,35,24,35,0.0,1.0
21,22,Male,25,24,73,0.0,1.0
22,23,Female,46,25,5,1.0,0.0
23,24,Male,31,25,73,0.0,1.0
24,25,Female,54,28,14,1.0,0.0
25,26,Male,29,28,82,0.0,1.0
26,27,Female,45,28,32,1.0,0.0
27,28,Male,35,28,61,0.0,1.0
28,29,Female,40,29,31,1.0,0.0
29,30,Female,23,29,87,1.0,0.0
...,...,...,...,...,...,...,...
170,171,Male,40,87,13,0.0,1.0
171,172,Male,28,87,75,0.0,1.0
172,173,Male,36,87,10,0.0,1.0
173,174,Male,36,87,92,0.0,1.0
174,175,Female,52,88,13,1.0,0.0
175,176,Female,30,88,86,1.0,0.0
176,177,Male,58,88,15,0.0,1.0
177,178,Male,27,88,69,0.0,1.0
178,179,Male,59,93,14,0.0,1.0
179,180,Male,35,93,90,0.0,1.0
180,181,Female,37,97,32,1.0,0.0
181,182,Female,32,97,86,1.0,0.0
182,183,Male,46,98,15,0.0,1.0
183,184,Female,29,98,88,1.0,0.0
184,185,Female,41,99,39,1.0,0.0
185,186,Male,30,99,97,0.0,1.0
186,187,Female,54,101,24,1.0,0.0
187,188,Male,28,101,68,0.0,1.0
188,189,Female,41,103,17,1.0,0.0
189,190,Female,36,103,85,1.0,0.0
190,191,Female,34,103,23,1.0,0.0
191,192,Female,32,103,69,1.0,0.0
192,193,Male,33,113,8,0.0,1.0
193,194,Female,38,113,91,1.0,0.0
194,195,Female,47,120,16,1.0,0.0
195,196,Female,35,120,79,1.0,0.0
196,197,Female,45,126,28,1.0,0.0
197,198,Male,32,126,74,0.0,1.0
198,199,Male,32,137,18,0.0,1.0
199,200,Male,30,137,83,0.0,1.0

In [11]:
#iris data set
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
cols = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']
iris = pd.read_csv(url, names=cols)

# For each species:
print("Setosa:\n", iris[iris['Species']=='Iris-setosa'].describe())
print("Versicolor:\n", iris[iris['Species']=='Iris-versicolor'].describe())
print("Virginica:\n", iris[iris['Species']=='Iris-virginica'].describe())

('Setosa:\n',        Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count      50.00000    50.000000     50.000000     50.00000
mean        5.00600     3.418000      1.464000      0.24400
std         0.35249     0.381024      0.173511      0.10721
min         4.30000     2.300000      1.000000      0.10000
25%         4.80000     3.125000      1.400000      0.20000
50%         5.00000     3.400000      1.500000      0.20000
75%         5.20000     3.675000      1.575000      0.30000
max         5.80000     4.400000      1.900000      0.60000)
('Versicolor:\n',        Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000)
('Virginica:\n',        Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000)